### ISSUE TITLE
Start Playing from HomeScreen

### ISSUE THREAD

**Issue by tuvakov** [SaraHan774/Jetcaster#20]
- Start and stop playing directly from the Home Screen
- Make sure Play/Pause state of the episode is reflected well in the Home Screen

**Comment by SaraHan774** [comment]
AS-IS : 이미 재생중인 아이템 항목을 클릭해서 들어가더라도 재생이 처음부터 다시 시작된다 
TO-BE : 홈 화면으로 돌아왔을 때 재생중인 디테일 화면으로 다시 돌아갈 수 있는 플레이어바를 추가

**Comment by SaraHan774** [comment]
<img width="418" alt="image" src="https://github.com/SaraHan774/Jetcaster/assets/42170276/d12d9043-7951-4cae-aa5d-c31e1ba066e2">

**Comment by SaraHan774** [comment]
현재 구조의 PlayerViewModel 은 Navigation 시에 episodeUri 를 받아서 초기화 한다 
ViewState 또한 하나의 에피소드에 대해서만 구성이 되어있다 
리스트 아이템으로부터 플레이를 시작하려면 Play 버튼 클릭 시 클릭된 에피소드에 대한 정보만을 PlayerViewModel 이 받아서 처리하도록 해야한다.
