### ISSUE TITLE
Introduce Dagger Hilt

### ISSUE THREAD

**Issue by tuvakov** [SaraHan774/Jetcaster#9]
Migrate current dependency injection to Dagger Hilt

**Comment by SaraHan774** [comment]
현재 구조에서 hilt 의존성 주입 + ViewModel + Compose 세팅하는데 약간 까다로운 부분이 있어서 작업이 느린 상태입니다 ㅠ

**Comment by tuvakov** [comment]
> 현재 구조에서 hilt 의존성 주입 + ViewModel + Compose 세팅하는데 약간 까다로운 부분이 있어서 작업이 느린 상태입니다 ㅠ

아 네네, 알겠습니다~
